import type { BackgroundToken } from '../types'
import { TOKEN_NOT_FOUND } from '../constants'

const tokens: Record<`$.${BackgroundToken}`, string> = {
  '$.accent.neutral.lighter': 'var(--N100)',
  '$.accent.neutral.light': 'var(--N200)',
  '$.accent.neutral': 'var(--N300)',
  '$.accent.neutral.bold': 'var(--N600)',
  '$.accent.neutral.bolder': 'var(--N800)',
  '$.accent.blue.lighter': 'var(--B100)',
  '$.accent.blue.light': 'var(--B200)',
  '$.accent.blue': 'var(--B400)',
  '$.accent.blue.bold': 'var(--B600)',
  '$.accent.blue.bolder': 'var(--B800)',
  '$.accent.red.lighter': 'var(--R100)',
  '$.accent.red.light': 'var(--R200)',
  '$.accent.red': 'var(--R400)',
  '$.accent.red.bold': 'var(--R600)',
  '$.accent.red.bolder': 'var(--R800)',
  '$.accent.orange.lighter': 'var(--O100)',
  '$.accent.orange.light': 'var(--O200)',
  '$.accent.orange': 'var(--O400)',
  '$.accent.orange.bold': 'var(--O600)',
  '$.accent.orange.bolder': 'var(--O800)',
  '$.accent.yellow.lighter': 'var(--Y100)',
  '$.accent.yellow.light': 'var(--Y200)',
  '$.accent.yellow': 'var(--Y400)',
  '$.accent.yellow.bold': 'var(--Y600)',
  '$.accent.yellow.bolder': 'var(--Y800)',
  '$.accent.green.lighter': 'var(--G100)',
  '$.accent.green.light': 'var(--G200)',
  '$.accent.green': 'var(--G400)',
  '$.accent.green.bold': 'var(--G600)',
  '$.accent.green.bolder': 'var(--G800)',
  '$.accent.purple.lighter': 'var(--P100)',
  '$.accent.purple.light': 'var(--P200)',
  '$.accent.purple': 'var(--P400)',
  '$.accent.purple.bold': 'var(--P600)',
  '$.accent.purple.bolder': 'var(--P800)',
  '$.accent.teal.lighter': 'var(--T100)',
  '$.accent.teal.light': 'var(--T200)',
  '$.accent.teal': 'var(--T400)',
  '$.accent.teal.bold': 'var(--T600)',
  '$.accent.teal.bolder': 'var(--T800)',
  '$.accent.magenta.lighter': 'var(--M100)',
  '$.accent.magenta.light': 'var(--M200)',
  '$.accent.magenta': 'var(--M400)',
  '$.accent.magenta.bold': 'var(--M600)',
  '$.accent.magenta.bolder': 'var(--M800)',

  '$.neutral': 'var(--N200A)',
  '$.neutral.hover': 'var(--N300A)',
  '$.neutral.active': 'var(--N400A)',
  '$.neutral.bold': 'var(--N600)',
  '$.neutral.bold.hover': 'var(--N700)',
  '$.neutral.bold.active': 'var(--N800)',
  '$.error': 'var(--R100)',
  '$.error.hover': 'var(--R200)',
  '$.error.active': 'var(--R300)',
  '$.error.bold': 'var(--R600)',
  '$.error.bold.hover': 'var(--R700)',
  '$.error.bold.active': 'var(--R800)',
  '$.info': 'var(--B100)',
  '$.info.hover': 'var(--B200)',
  '$.info.active': 'var(--B300)',
  '$.info.bold': 'var(--B600)',
  '$.info.bold.hover': 'var(--B700)',
  '$.info.bold.active': 'var(--B800)',
  '$.help': 'var(--P100)',
  '$.help.hover': 'var(--P200)',
  '$.help.active': 'var(--P300)',
  '$.help.bold': 'var(--P600)',
  '$.help.bold.hover': 'var(--P700)',
  '$.help.bold.active': 'var(--P800)',
  '$.success': 'var(--G100)',
  '$.success.hover': 'var(--G200)',
  '$.success.active': 'var(--G300)',
  '$.success.bold': 'var(--G600)',
  '$.success.bold.hover': 'var(--G700)',
  '$.success.bold.active': 'var(--G800)',
  '$.warning': 'var(--Y100)',
  '$.warning.hover': 'var(--Y200)',
  '$.warning.active': 'var(--Y300)',
  '$.warning.bold': 'var(--Y600)',
  '$.warning.bold.hover': 'var(--Y700)',
  '$.warning.bold.active': 'var(--Y800)',

  '$.button': 'var(--N0)',
  '$.button.hover': 'var(--N100)',
  '$.button.active': 'var(--N200)',
  '$.input': 'var(--N0)',
  '$.input.hover': 'var(--N100)',
  '$.input.active': 'var(--N200)',

  '$.blanket': 'var(--N500A)',
  '$.skeleton': 'var(--N200A)',
  '$.inverse': 'var(--N1000)',
  '$.default': 'var(--N0)',
}

export function background(name: BackgroundToken = 'default') {
  return tokens[`$.${name}`] || TOKEN_NOT_FOUND
}
